### ISSUE TITLE
Could you add a kotlin module?

### ISSUE THREAD

**Issue by elect86** [jjohannes/gradle-jpms-experiments#1]
As titled, I'd like to see how the new JPMS Gradle works out with Kotlin.

Till now I always had to type: 

```
compileJava {
    dependsOn(':compileKotlin')
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath,
                '--patch-module', "$moduleName=${sourceSets["main"].output.asPath}"]
        classpath = files()
    }
}
```

However, commenting that and adding

```
plugins.withType(JavaPlugin).configureEach {
    java {
        modularity.inferModulePath = true
    }
}
```

brings errors about modules (eg `kotlin.stdlib`) not being found

**Comment by jjohannes** [comment]
@elect86 the issue is that the Kotlin libraries do not set an _automatic module name_. Then Gradle does not treat them as modules (see https://github.com/gradle/gradle/issues/12630 for further discussions). I think the Kotlin libraries should publish their _automatic module names_ in their manifest files, since they are clearly aware of them as the specific error message you get from the Kotlin plugin shows. I'll open an issue there.

I have published a small plugin that allows you to add the missing information to the jars. You can use that for now in the Kotlin context. I added a small example:

https://github.com/jjohannes/gradle-jpms-experiments/blob/master/module-kotlin/build.gradle.kts

**Comment by TheMrMilchmann** [comment]
There has been [an issue for adding explicit module descriptors to the Kotlin stdlib](https://youtrack.jetbrains.com/issue/KT-21266) for quite a while now. It was attempted multiple times but delayed due to tooling issues (and is currently targeting 1.4). However, while they have added neither explicit descriptors nor an Automatic-Module-Name to the **default** stdlib artifacts, there are fully modular artifacts available and [published with the "modular" classifier](https://youtrack.jetbrains.com/issue/KT-27919).

**Comment by ilya-g** [comment]
We're going to add module info to Kotlin standard library artifacts in 1.4.

**Comment by ilya-g** [comment]
@jjohannes Could you improve the example by adding an export of the package and adding some black-box tests?
I suspect https://github.com/gradle/gradle/issues/8897 is still not fixed for mixed kotlin/java projects that apply `java-library` plugin: the test compilation gets main sourceset dependency in an exploded form.

**Comment by jjohannes** [comment]
Thanks for the additional context @TheMrMilchmann  and @ilya-g.

I changed the sample to use the "modular" version of the standard library. It's good to know that it'll _just work_ with Kotlin 1.4 then.

Regarding testing: This is a general thing with Modules as discussed for example [here](https://github.com/gradle/gradle/issues/890#issuecomment-613427968). It's not really a bug but a question of how you setup your tests. I now added one way to do it in the sample. There the tests depend on the project itself and will then get the "main variant" (the jar) on their classpath.

As I wrote in the comment I linked, we are considering adding some conveniences to Gradle soon to make such test setup simpler for users.

**Comment by jjohannes** [comment]
One thing that remains is that you still need to do
```
tasks.compileJava {
    options.compilerArgs = listOf("--patch-module", "org.module.kotlin=${sourceSets.main.get().output.asPath}")
}
```
if you split up compilation of one source set by using multiple folder (e.g. `main/kotlin` and `main/java`). That's something we could somehow do automatically I think.

This is related to better "SourceDirectorySet" (https://github.com/gradle/gradle/issues/727) APIs. I'll add a note to that issue. If we address this, it will also become easier for the Kotlin plugin (and others) to wire in their additional compile tasks and we could use that information to automatically add `--patch-module` statements if required.

**Comment by ilya-g** [comment]
> One thing that remains is that you still need to do ... if you split up compilation of one source set by using multiple folder (e.g. main/kotlin and main/java).

It is not essential how sources are laid out (in just main/java or in main/kotlin + main/java). What is essential is that we anyway have two compilations here, one with Kotlin and one with Java compiler, and each of them generates results in a separate output folder.

If you inspect `compileTestJava` task classpath, you'll see that it depends on the main compilation results in the following way:
```
gradle-jpms-experiments\module-kotlin\build\classes\java\main
gradle-jpms-experiments\module-kotlin\build\classes\kotlin\main
gradle-jpms-experiments\module-kotlin\build\resources\main
```
That is the situation when module content is split between multiple folders.

I see that you've used an interesting trick in the `integTest` sourceset dependencies:
```
    "integTestImplementation"(project)
```
This way integTest compilations get a dependency on the consolidated jar:
```
gradle-jpms-experiments\module-kotlin\build\libs\module-kotlin-0.9-beta.jar
```

However there's still the same problem in the `integTest` task runtime classpath:
```
gradle-jpms-experiments\module-kotlin\build\classes\java\integTest
gradle-jpms-experiments\module-kotlin\build\classes\kotlin\integTest
gradle-jpms-experiments\module-kotlin\build\resources\integTest
gradle-jpms-experiments\module-kotlin\build\libs\module-kotlin-0.9-beta.jar
```
This way neither the result of integTest sourceset's Kotlin compilation, nor its resources will be considered as a part of `org.module.kotlin.integtest` module.

**Comment by jjohannes** [comment]
> However there's still the same problem in the integTest task runtime classpath:

Yes. Right. That's another detail with the test setup (independent of Kotlin) that can also be solved. I updated the sample again :) https://github.com/jjohannes/gradle-jpms-experiments/commit/48b28c2ca646478b168b5892845aacc8c35cd17f

Basically in the module world, packaging a `Jar` has much more meaning, because if everything is cleanly done: "one module" == "one jar". So I think it makes sense to move towards using Jars everywhere instead of _classes_ folders once you are in the module world. (For example, it is also needed to discover automatic module names which are stored in Jar manifests.)

See also discussion around [this comment](https://github.com/gradle/gradle/issues/890#issuecomment-611592961) and this [sample from in the Gradle docs](https://docs.gradle.org/6.4-rc-2/samples/sample_java_modules_multi_project_with_integration_tests.html).

We will also consider this aspect when we add more conveniences for test setup. We should consider making the "using the Jar" the default when your _test source set_ is a module.

**Comment by ilya-g** [comment]
Thank you for updating the sample.

>  "one module" == "one jar". So I think it makes sense to move towards using Jars everywhere instead of classes folders once you are in the module world. 

Indeed, it makes sense, and would significantly simplify the test setup if all what is needed is black-box testing: that would remove the need to setup a separate integTest source set.

**Comment by elect86** [comment]
@jjohannes how do I translate that in Groovy? (I'm trying without the `integTest` atm)

I think I managed the `configuration` part

```
configurations.all {
    if (name.toLowerCase().endsWith("compileclasspath") || name.toLowerCase().endsWith("runtimeclasspath")) {
        attributes.attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, project.objects.named(LibraryElements, "modular-jar"))
    }
    if (name.toLowerCase().endsWith("compile") || name.toLowerCase().endsWith("runtime")) {
        isCanBeConsumed = false
    }
}
```
But what about the `dependecies`?

this

```
dependencies {
    attributesSchema.attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE).compatibilityRules.add(ModularJarCompatibilityRule::class)
    components { withModule<ModularKotlinRule>(kotlin("stdlib")) }
```

fires the following:

> Build file 'C:\Users\elect\IdeaProjects\kotlin-unsigned\build.gradle' line: 21

> Could not compile build file 'C:\Users\elect\IdeaProjects\kotlin-unsigned\build.gradle'.
> startup failed:
  build file 'C:\Users\elect\IdeaProjects\kotlin-unsigned\build.gradle': 21: unexpected token: : @ line 21, column 144.
     , ModularJarCompatibilityRule::class)

**Comment by jjohannes** [comment]
@elect86 You have to reference the Java _class_ objects in Groovy (just the class name `ModularJarCompatibilityRule` or with .class like in Java `ModularJarCompatibilityRule.class`). It should look like this (haven't tested):

```
attributesSchema.attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE).compatibilityRules.add(ModularJarCompatibilityRule)
    components { withModule(kotlin("stdlib"), ModularJarCompatibilityRule) }
```

**Comment by elect86** [comment]
I bite the bullet and switched to [kts](https://github.com/kotlin-graphics/kotlin-unsigned/blob/jpms/build.gradle.kts)

I still get:

> C:\Users\elect\IdeaProjects\kotlin-unsigned\src\main\java\module-info.java:4: error: module not found: kotlin.stdlib.jdk8

What am I doing wrong?

**Comment by elect86** [comment]
It works if I use kotlin `stdlib` but it fails with `stdlib-jdk8`

> e: Module kotlin.stdlib cannot be found in the module graph

Edit: [solved](https://stackoverflow.com/questions/61638287/gradle-6-4-kotlin-and-jpms/61766500?noredirect=1#comment109264242_61766500)

**Comment by elect86** [comment]
@jjohannes any change with Kotlin 1.4.0?

**Comment by jjohannes** [comment]
@elect86 thanks for asking. With Kotlin 1.4.0 things now work out-of-the-box as the standard library is a multi-release JAR that contains a `module-info.class` for Java 9+. I updated the sample: https://github.com/jjohannes/gradle-jpms-experiments/commit/1b4604fed93a0b675087ece37da86ae548281f2a

**Comment by elect86** [comment]
This is nice, thanks
